// ═══════════════════════════════════════════════════════════
// ShadchanAI — Semantic Backfill (on-demand "סרוק עכשיו")
//
// Embeds every active candidate whose vectors are missing OR were
// generated by a different model than the one currently configured
// (provider/model switch ⇒ stale vector space). Unlike the per-scan
// lazy pass (ensureEmbeddingsForScan, capped at 200), this job aims
// for FULL coverage in one run — it's the button behind the
// "הצעה חכמה" tab.
//
// Job model: single-instance server ⇒ in-memory singleton state +
// in-flight lock (same approach as match-scan's scanInFlight). The
// client polls getSemanticBackfillState() every second while running.
// ═══════════════════════════════════════════════════════════

import { InternalCandidate, ExternalCandidate } from '../../models/index.js';
import { ensureAllChunks } from './embedding.service.js';
import { getEmbeddingProvider } from './embedding.provider.js';
import { isSemanticEnabled } from './embedding.gate.js';
import { BusinessRuleError } from '../../utils/errors.js';
import { createLogger } from '../../utils/logger.js';

const log = createLogger('semantic.backfill');

const EMBED_CONCURRENCY = 4;

export interface SemanticBackfillState {
  status: 'idle' | 'running' | 'done' | 'error';
  /** 'delta' = only candidates missing/stale vectors; 'force' = full sweep over ALL active candidates. */
  mode?: 'delta' | 'force';
  progressCurrent: number;
  progressTotal: number;
  embedded: number;
  failed: number;
  /** Candidates whose profile has no embeddable text at all — they CANNOT enter the vector space until data is added. */
  noContent: number;
  startedAt?: string;
  finishedAt?: string;
  lastError?: string;
}

let state: SemanticBackfillState = {
  status: 'idle',
  progressCurrent: 0,
  progressTotal: 0,
  embedded: 0,
  failed: 0,
  noContent: 0,
};
let backfillInFlight = false;

export function getSemanticBackfillState(): SemanticBackfillState {
  return { ...state };
}

/**
 * Kicks off the backfill in the background and returns the current
 * state immediately. A second call while running is a no-op that
 * returns the live state (idempotent button).
 *
 * force=true sweeps EVERY active candidate — including those whose
 * embedding.modelId is current but who never actually got vectors
 * (partial/no-content profiles that the delta filter skips). Fresh
 * chunks are still skipped per-chunk, so a force run only pays for
 * the gaps, not for re-embedding the whole pool.
 */
export async function startSemanticBackfill(
  options: { force?: boolean } = {},
): Promise<SemanticBackfillState> {
  if (!(await isSemanticEnabled())) {
    throw new BusinessRuleError(
      'התאמה סמנטית כבויה — הפעל אותה בהגדרות ← כללי התאמה לפני סריקה',
      { code: 'semantic_disabled' },
    );
  }
  if (backfillInFlight) return getSemanticBackfillState();

  const force = options.force === true;
  backfillInFlight = true;
  state = {
    status: 'running',
    mode: force ? 'force' : 'delta',
    progressCurrent: 0,
    progressTotal: 0,
    embedded: 0,
    failed: 0,
    noContent: 0,
    startedAt: new Date().toISOString(),
  };

  void runBackfill(force)
    .catch((err) => {
      state.status = 'error';
      state.lastError = String(err);
      log.error({ error: String(err) }, 'backfill_failed');
    })
    .finally(() => {
      backfillInFlight = false;
      state.finishedAt = new Date().toISOString();
      if (state.status === 'running') state.status = 'done';
    });

  return getSemanticBackfillState();
}

async function runBackfill(force: boolean): Promise<void> {
  const currentModelId = getEmbeddingProvider().modelConfig.modelId;

  // Delta: missing vectors OR vectors from another model (unusable for
  // cosine against the current model's space). Force: every active
  // candidate — catches profiles the delta filter misses (modelId set
  // but some chunks never embedded). Only active candidates either
  // way — no point paying for archived/closed profiles.
  const filter = force
    ? { status: 'active' }
    : {
        status: 'active',
        $or: [
          { 'embedding.modelId': { $exists: false } },
          { 'embedding.modelId': { $ne: currentModelId } },
        ],
      };

  const [internals, externals] = await Promise.all([
    InternalCandidate.find(filter).select('_id').lean().exec(),
    ExternalCandidate.find(filter).select('_id').lean().exec(),
  ]);

  const targets: Array<{ id: string; type: 'internal' | 'external' }> = [
    ...internals.map((d) => ({ id: String(d._id), type: 'internal' as const })),
    ...externals.map((d) => ({ id: String(d._id), type: 'external' as const })),
  ];

  state.progressTotal = targets.length;
  log.info({ total: targets.length, model: currentModelId, force }, 'backfill_started');

  for (let i = 0; i < targets.length; i += EMBED_CONCURRENCY) {
    const slice = targets.slice(i, i + EMBED_CONCURRENCY);
    const results = await Promise.allSettled(
      slice.map((t) => ensureAllChunks(t.id, t.type)),
    );
    for (let j = 0; j < results.length; j++) {
      const r = results[j]!;
      if (r.status === 'fulfilled') {
        // 'fresh' counts as embedded coverage; 'no_content' is surfaced
        // separately so the operator knows WHY a candidate stays out.
        if (r.value === 'no_content') state.noContent++;
        else state.embedded++;
      } else {
        state.failed++;
        log.warn({ ...slice[j], error: String((r as PromiseRejectedResult).reason) }, 'backfill_embed_failed');
      }
      state.progressCurrent++;
    }
  }

  log.info(
    { embedded: state.embedded, failed: state.failed, noContent: state.noContent, force },
    'backfill_finished',
  );
}
