// ═══════════════════════════════════════════════════════════
// ShadchanAI — Semantic Backfill (on-demand "סרוק עכשיו")
//
// Embeds every active candidate whose vectors are missing OR were
// generated by a different model than the one currently configured
// (provider/model switch ⇒ stale vector space). Unlike the per-scan
// lazy pass (ensureEmbeddingsForScan, capped at 200), this job aims
// for FULL coverage in one run — it's the button behind the
// "הצעה חכמה" tab.
//
// Job model: single-instance server ⇒ in-memory singleton state +
// in-flight lock (same approach as match-scan's scanInFlight). The
// client polls getSemanticBackfillState() every second while running.
// ═══════════════════════════════════════════════════════════

import { InternalCandidate, ExternalCandidate } from '../../models/index.js';
import { ensureAllChunks } from './embedding.service.js';
import { getEmbeddingProvider } from './embedding.provider.js';
import { isSemanticEnabled } from './embedding.gate.js';
import { BusinessRuleError } from '../../utils/errors.js';
import { createLogger } from '../../utils/logger.js';

const log = createLogger('semantic.backfill');

const EMBED_CONCURRENCY = 4;

export interface SemanticBackfillState {
  status: 'idle' | 'running' | 'done' | 'error';
  progressCurrent: number;
  progressTotal: number;
  embedded: number;
  failed: number;
  startedAt?: string;
  finishedAt?: string;
  lastError?: string;
}

let state: SemanticBackfillState = {
  status: 'idle',
  progressCurrent: 0,
  progressTotal: 0,
  embedded: 0,
  failed: 0,
};
let backfillInFlight = false;

export function getSemanticBackfillState(): SemanticBackfillState {
  return { ...state };
}

/**
 * Kicks off the backfill in the background and returns the current
 * state immediately. A second call while running is a no-op that
 * returns the live state (idempotent button).
 */
export async function startSemanticBackfill(): Promise<SemanticBackfillState> {
  if (!(await isSemanticEnabled())) {
    throw new BusinessRuleError(
      'התאמה סמנטית כבויה — הפעל אותה בהגדרות ← כללי התאמה לפני סריקה',
      { code: 'semantic_disabled' },
    );
  }
  if (backfillInFlight) return getSemanticBackfillState();

  backfillInFlight = true;
  state = {
    status: 'running',
    progressCurrent: 0,
    progressTotal: 0,
    embedded: 0,
    failed: 0,
    startedAt: new Date().toISOString(),
  };

  void runBackfill()
    .catch((err) => {
      state.status = 'error';
      state.lastError = String(err);
      log.error({ error: String(err) }, 'backfill_failed');
    })
    .finally(() => {
      backfillInFlight = false;
      state.finishedAt = new Date().toISOString();
      if (state.status === 'running') state.status = 'done';
    });

  return getSemanticBackfillState();
}

async function runBackfill(): Promise<void> {
  const currentModelId = getEmbeddingProvider().modelConfig.modelId;

  // Missing vectors OR vectors from another model (unusable for cosine
  // against the current model's space). Only active candidates — no
  // point paying for archived/closed profiles.
  const staleFilter = {
    status: 'active',
    $or: [
      { 'embedding.modelId': { $exists: false } },
      { 'embedding.modelId': { $ne: currentModelId } },
    ],
  };

  const [internals, externals] = await Promise.all([
    InternalCandidate.find(staleFilter).select('_id').lean().exec(),
    ExternalCandidate.find(staleFilter).select('_id').lean().exec(),
  ]);

  const targets: Array<{ id: string; type: 'internal' | 'external' }> = [
    ...internals.map((d) => ({ id: String(d._id), type: 'internal' as const })),
    ...externals.map((d) => ({ id: String(d._id), type: 'external' as const })),
  ];

  state.progressTotal = targets.length;
  log.info({ total: targets.length, model: currentModelId }, 'backfill_started');

  for (let i = 0; i < targets.length; i += EMBED_CONCURRENCY) {
    const slice = targets.slice(i, i + EMBED_CONCURRENCY);
    const results = await Promise.allSettled(
      slice.map((t) => ensureAllChunks(t.id, t.type)),
    );
    for (let j = 0; j < results.length; j++) {
      if (results[j]!.status === 'fulfilled') {
        state.embedded++;
      } else {
        state.failed++;
        const r = results[j] as PromiseRejectedResult;
        log.warn({ ...slice[j], error: String(r.reason) }, 'backfill_embed_failed');
      }
      state.progressCurrent++;
    }
  }

  log.info(
    { embedded: state.embedded, failed: state.failed },
    'backfill_finished',
  );
}
